CREATE DATABASE IF NOT EXISTS news CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE news;

CREATE TABLE IF NOT EXISTS newscount (
  name VARCHAR(255) NOT NULL,
  count BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS periodcount (
  logtime VARCHAR(64) NOT NULL,
  count BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY (logtime)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
